#!/usr/bin/env bun

// Reads runtime source files and generates src/runtime/embedded.js
// with their contents as exported string constants.
// This allows the compiled binary to work without the source tree.

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const runtimeDir = join(__dirname, '..', 'src', 'runtime');
const outFile = join(runtimeDir, 'embedded.js');

const files = {
  REACTIVITY_SOURCE: 'reactivity.js',
  RPC_SOURCE: 'rpc.js',
  ROUTER_SOURCE: 'router.js',
  DEVTOOLS_SOURCE: 'devtools.js',
};

let output = '// Auto-generated by scripts/embed-runtime.js — do not edit\n\n';

for (const [varName, filename] of Object.entries(files)) {
  const content = readFileSync(join(runtimeDir, filename), 'utf-8');
  output += `export const ${varName} = ${JSON.stringify(content)};\n\n`;
}

writeFileSync(outFile, output);
console.log(`Generated ${outFile}`);

// Also embed version from package.json so the compiled binary doesn't need it at runtime
const pkg = JSON.parse(readFileSync(join(__dirname, '..', 'package.json'), 'utf-8'));
const versionFile = join(__dirname, '..', 'src', 'version.js');
writeFileSync(versionFile, `// Auto-generated by scripts/embed-runtime.js — do not edit\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`);
console.log(`Generated ${versionFile}`);
